### ISSUE TITLE
Empty hand bug with the latest hotfix (1.1.6)

### ISSUE THREAD

**Issue by carlo-rigacci** [blat-blatnik/TFC-Quick-Pockets#12]
![tfcpocketsbug](https://user-images.githubusercontent.com/72162133/108638767-2aad1c00-7491-11eb-84ea-f237aec56bcd.png)
The crash on startup has been fixed. Thank you for that and for the quick response 🙂However there is a new issue now that only appears in 1.1.6: As in the above screenshot, if you attempt to scroll through items in the hotbar, the active slot will immediately switch to the next available item, skipping over empty slots entirely. This makes it so that it is only possible to have an empty hand if you manually press the assigned key for the empty slot (In the case above: keys 4, 5 and 6), drop the item, or go into your inventory and move the item (either by dragging or click-dropping into a different slot) from the active slot into a different slot, thus freeing your hand.

**Comment by blat-blatnik** [comment]
Yes this is intentional since version 1.1.6. You can turn it off in the mod config menu under _Hotbar Cycling_ if you prefer the vanilla behavior.
